### ISSUE TITLE
Packaging this as library?

### ISSUE THREAD

**Issue by merijn** [weeezes/plot#10]
Hey, this stuff looks pretty cool and like something I could use, but in its current form it's only about 90% of the way there. I don't mind finishing up the last 10%, I was just wondering if you had any plans to revisit/maintain this in the future or whether or I should fork it and take up the maintenance myself.

**Comment by weeezes** [comment]
Hey! Whichever you feel more comfortable with is fine for me :). 

I haven't had that many ideas on what to do next with the project so it's a bit forgotten, but if you have any ideas which you'd like to collaborate on I'm in! But also feel free to fork and walk your own path 👍
